### ISSUE TITLE
MCCP2 starts too late in the stream

### ISSUE THREAD

**Issue by bofh69** [LiquidityC/Blightmud#139]
**Describe the bug**
When the TelnetEvents::Subnegotiation event about opt::MCCP2 is received, the zlib-stream starts on the next byte from the TCP-stream, but that is too late. There can be more bytes buffered in the libtelnet_rs::Parser's buffer and they will be parsed there. This leads to data corruption of the received bytes.

**To Reproduce**
Connect to dum.acc.umu.se 2001. It outputs a lot of telnet options and text before it starts MCCP2. Wait a few seconds for it to fail its IDENT lookup, then the login prompt shows up. Before the login prompt there will now be garbage text.

**What terminal are you using?**
gnome-terminal

**What mud were you playing?**
DUMII: dum.acc.umu.se 2001

**Screenshots**
![image](https://user-images.githubusercontent.com/1444315/96377061-1f647f80-1183-11eb-860b-06a61b352f05.png)

**Comment by LiquidityC** [comment]
Yeah, I've done the best I can with what we've got here. You get the garbage characters but at least it doesn't corrupt the stream and disconnect which was a problem before.

Perhaps I should just get around to "nipping this in the bud".

I've committed one or two things before to libtelnet-rs. Since it's rust it's not to hard to work with. Also @envis10n is a nice guy. If you feel like taking a swing at it @bofh69 :wink: 

If not, I'll get to it eventually.

**Comment by envis10n** [comment]
I'm working on it as we speak :)

@bofh69 would you mind hitting me up on discord so I can ask you a few questions?

**Comment by LiquidityC** [comment]
Hey @bofh69 this should no longer be an issue. Thanks for shaking the tree on this issue. :smile:

**Comment by LiquidityC** [comment]
Come to think of it. The handling I just added should allow a more graceful "disable MCCP2". Eg. If it's on already and we get this event that most likely means that we should disable MCCP2. This was not possible/easy before. I can't think of many usecases where you would disable MCCP2 mid game. But according to protocol we should probably support it. I just couldn't be bothered.

**Comment by bofh69** [comment]
You guys are amazing! Thanks!
