### ISSUE TITLE
Client crash if you type odd keys in prompt

### ISSUE THREAD

**Issue by LiquidityC** [LiquidityC/Blightmud#155]
**Describe the bug**
When typing 'ÄÖÅ' into prompt blightmud will crash

**To Reproduce**
Start blightmud and type Ä, Ö or Å

**REPORT:**
```toml
name = 'blightmud'
operating_system = 'unix:Arch'
crate_version = '2.1.0'
explanation = '''
Panic occurred in file '/home/linus/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/string.rs' at line 1291
'''
cause = 'assertion failed: self.is_char_boundary(idx)'
method = 'Panic'
backtrace = '''

   0: 0x565081add76d - core::panicking::panic::h4b079e3c35cc1b09
                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:50
   1: 0x5650817a6abe - blightmud::ui::command::parse_key_event::h4635b2240fc32314
   2: 0x5650817ce2db - std::sys_common::backtrace::__rust_begin_short_backtrace::hf71f1c62474ae76a
   3: 0x565081727d09 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h0caf8ddc7c80c4bf
   4: 0x565081ac326a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h670c50864ac2cb92
                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/alloc/src/boxed.rs:1042
                 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h2511952749086d81
                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/alloc/src/boxed.rs:1042
                 - std::sys::unix::thread::Thread::new::thread_start::h5ad4ddffe24373a8
                at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys/unix/thread.rs:87
   5: 0x7fa80ec673e9 - start_thread
   6: 0x7fa80eb79293 - __GI___clone
   7:        0x0 - <unresolved>'''
```

**Comment by xvxx** [comment]
This is because we are mixing two different ways of indexing Rust strings: unicode character points and bytes.

For documentation, here's the issue:

```rust
fn main() {
    let s = "Löwe";
    println!("{:?}", s);
    println!("{:?}", s.len());
    println!("{:?}", s.chars().count());
}
```

This will print:

```
"Löwe"
5
4
```

As you can see, this string is five bytes but only four characters. Most string operations use byte positions, such as `replace_range()` and `len()` and `insert()`, which can fail if the byte is part of a `char`.

Our `cursor_pos` handling uses bytes, which means sometimes Blightmud will think our cursor is "inside" a multi-byte char, leading to the panic in this issue:

```rust
fn main() {
    let mut s = "Löwe".to_string();
    s.insert(2, 'c');
}

thread 'main' panicked at 'assertion failed: self.is_char_boundary(idx)', /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/alloc/src/string.rs:1291:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I think our best bet is to keep most of the code the same, but change the math we use to update `cursor_pos`. When you "move right" using an arrow key, we need to say "set `cursor_pos` to the first byte of the next `char`", instead of just `cursor_pos += 1`. Then we can still use `replace_range()` and friends, and it should all Just Work.

**Comment by LiquidityC** [comment]
Digging into this now. This is an easy mistake to make on my keyboard :smile:

**Comment by LiquidityC** [comment]
This one wasn't easy. Currently the `cursor_pos` is used when the prompt content is sent to screen. I think we need to maintain different indexes here. One for modifying and one for displaying. I'll need to fiddle slightly more with it.

**Comment by LiquidityC** [comment]
Ok, submitting a fix for this now. Here's the solution. We won't hold the input buffer as a string any longer. It's now a `Vec<char>` that way we never need to be concerned with byte size and utf8 encoding issues since the rust `char` is 4 `bytes` and can hold all utf8 chars.

Thank god for unit testing though. I feel rather confident that this change hasn't broken anything.
