### ISSUE TITLE
Crash when data/*.ron file is empty

### ISSUE THREAD

**Issue by xvxx** [LiquidityC/Blightmud#180]
On the `dev` branch:

```
$ touch data/servers.ron
$ cargo run
boom
```
Same thing for `data/history.ron`. I ended up with an empty `history.ron` while mucking around and noticed this.

**Comment by LiquidityC** [comment]
Yeah, I've countered some of these problems already. It's because I've left `unwraps` in the wild.

Here's how I feel we should fix this issue:

The trait `save.rs` has two methods: `save` and `load`. Both of these return a `Result<Self>` and `Result<()>` respectively. The trait requires the `Default` trait to be present on be present on the object. So, let's not have the `save` and `load` method return results. Let's make them consume their own errors and just return a loaded object or a default object. There is no point in returning Results. Since we don't care about the result in any place in the code.

**Comment by xvxx** [comment]
Great, thank you! Although I am surprised the deserializer `panic!`'d instead of returning an `Err()`? Since `ron::de::from_reader()` returns `Result`.
