### ISSUE TITLE
os.sleep() (or something...)

### ISSUE THREAD

**Issue by xvxx** [LiquidityC/Blightmud#183]
A MUD I play on tends to write directions like this:

    NEWBIE AREA  6n, 2w
    MID AREA     5s, 2w, Request Transit, Enter Module, 5s

So I added a little alias in Lua that lets me type `go 5n` to send `blight:send("n")` five times.

But, when doing lots of moves (like `go 15n`) I get rate limited - "You cannot move so fast!"

Lua doesn't come with `os.sleep()` and using `core:exec("sleep 1")` blocks the whole UI, so it'd be nice if there were a way to sleep between commands so I'm not overloading the server.

**Comment by Xandaros** [comment]
I don't think this is a good idea. What happens if you are sleeping and an event happens, like a trigger or a timer firing? Does it happen after the sleep finishes? Does it stop the code with the sleep?

Instead, I think you should just use a timer. You can store the list of moves in a table and when a timer fires, you make a move. Something like this:
```lua
moves = {}
blight:add_timer(1, 0, function()
    for _, move in ipairs(moves) do
        blight:send(table.remove(moves, 1))
    end
end)
```
You can then do something like `moves = ["n", "n", "n", "w"}` to set it going.

Alternatively, if you prefer to use an actual sleep, you can run it in a coroutine and use a timer to resume it:
```lua
tasks = {}
blight:add_timer(0.2, 0, function()
    for _, task in ipairs(tasks) do
        if os.time() > task[1] then
            local delay = coroutine.resume(task[2])
            task[1] = os.time() + delay
        end
    end
end)
```
You can then use it like this:
```lua
tasks[#tasks + 1] = {0, coroutine.create(function()
    for i = 1, 5 do
        blight:send("n")
        coroutine.yield(1)
    end
end)}
```
Untested, but you get the general idea.

**Comment by xvxx** [comment]
> What happens if you are sleeping and an event happens, like a trigger or a timer firing? Does it happen after the sleep finishes? Does it stop the code with the sleep?

Usually the `os.sleep()` is implemented as a coroutine in Lua (basically a timer behind the scenes), so everything else would happen normally. It wouldn't block other threads or coroutines. 

I haven't looked into how this would be implemented in Blightmud, but since the app is multithreaded it would probably be a similar principle.

**Comment by Xandaros** [comment]
Yeah, but they have a different architecture.

I think what I described is still the best option, but I can make a scheduler that is a bit more robust for inclusion in Blightmud.
You will have to create a task to use sleep, but I think that is actually a feature. It makes it obvious that only the task is sleeping, not everything else.

**Comment by xvxx** [comment]
You're right of course, but I think it's worth investigating the architectural changes to make something like this work.

I've noticed there's a few different ways to freeze the UI, and in my opinion that shouldn't be possible. You should be free to experiment with your Lua scripts without fear of crashing the app (unless you're using `debug` of course... ;). For example, you should be able to write an infinite loop in an `/alias` and have the app still work. Right now everything freezes. I have a hunch that the changes required to make that work would also support `sleep()`, so even if we never add `sleep()` it might be worth looking into.

If you are totally opposed to this I will defer to you, but I am interested in taking a stab at some of the architectural changes this would need. And I think they would have other, more important benefits, too.

**Comment by Xandaros** [comment]
Fair enough, that is a very good point.

We'd basically want to run everything in its own coroutine, which might actually be a good idea and would allow you to implement a sleep function.
To prevent infinite loops freezing everything, you might be able to use a hook trigger (like `every_nth_instruction`) to get a callback every so often and inject a yield.
Not sure how exactly that would work, but we'll see.

**Comment by LiquidityC** [comment]
I've got some input here. First of all, running alias and trigger callbacks in a thread becomes a very poor experience. It would be impossible to gag a trigger line from within the trigger callback because it has already printed before the callback has started. And users expect that responses to triggers appear on the line after the trigger line. Everything else becomes confusing. Even if it is faster.

If a user does implement an infinite loop we want him to notice and get problems. Otherwise it would be possible to create a massive amount of threads without really noticing which is also bad.

The whole running something in a separate thread idea is exactly how timers work right now. So if you need a way of sending a bunch of delayed commands I'd recommend leveraging that system.

Here is the code I use:
```lua
function delay(d, cmd, r)
    local count = 1
    if r ~= nil then
        count = r
    end
    blight:add_timer(d, count, function ()
        blight:send(cmd)
    end)
end

function queue(delay, cmds)
    blight:add_timer(delay, #cmds, function ()
        local cmd = cmds[1]
        table.remove(cmds, 1)
        blight:send(cmd)                      
    end)
end
```
We could add some standard functionality for this. But in my mind it should be done in the lua realm. It's true, blightmud is a threaded application but the way it threads isn't optimal (depends on your OS/Kernel/cpu) so I'd like to keep the amount of "spawning" to a fixed amount. I don't know how many threads we spawn currently, but it is always the same amount of threads and they keep alive for the duration of the execution/connection.

**Comment by LiquidityC** [comment]
Some of my previous comment was not correct. I didn't read properly or my knowledge about coroutines was 'limited'. But I still stand by the conclusion. If we add this we'll do it in the lua realm leveraging a trigger. :smi

**Comment by xvxx** [comment]
> If a user does implement an infinite loop we want him to notice and
get problems. Otherwise it would be possible to create a massive
amount of threads without really noticing which is also bad.

I agree, this would be all about the user experience. The goal would be to help people write scripts that don't break.

Right now you can type this into the prompt to freeze Blightmud:

    /lua while true do print 'oh no' end

The idea would be to run code as coroutines and return errors for those which don't yield in a certain amount of time, so instead of freezing you would see a number of "oh no" get printed to the screen and then you would see a regular Lua error:

```
> /lua while true do print 'oh no' end
oh no
oh no
oh no
...
[!!] [Lua] Script error:
[!!] 	runtime error: [string "return while true do print 'oh no' end"]:1: coroutine timed out
[!!] 	stack traceback:
[!!] 		[C]: in ?
[!!] 		[C]: in function 'error'
[!!] 		[string "return while true do print 'oh no' end"]:1: in local 'f'
[!!] 		[string "?"]:22: in function <[string "?"]:10>
```

I understand there are concerns around this, and rightfully so, so I think it's best to close this issue for now and resume the discussion if/when there's a Pull Request with a concrete idea on the table.

**Comment by xvxx** [comment]
@LiquidityC I don't think we would be spawning new threads for each chunk of code for this, but because we use threads we can do things like separate the Lua code that's running from the user input thread to prevent the UI from freezing.

> I don't know how many threads we spawn currently, but it is always the same amount of threads and they keep alive for the duration of the execution/connection.

This is the Linux command I use to see what threads a program is running, usually with a `watch` so it refreshes itself regularly:

    $ pstree -t (pidof blightmud)
    blightmud─┬─{Timer thread}
              └─6*[{blightmud}]

One thing we could do for better debuggability just in general,
outside any discussions of sleep/coroutines/etc, is name the threads.
So instead of using `thread::spawn(||{})` we would use
`thread::Builder::new().name("thread name".to_string()).spawn(||{})`
to spawn them and then see their names in the `pstree` output:

    pstree -t (pidof blightmud)
    blightmud─┬─{Timer thread}
              ├─3*[{blightmud}]
              ├─{input thread}
              ├─{receiver}
              └─{transmitter}

**Comment by LiquidityC** [comment]
Before we close this. Here is a direction I'm considering for the next major release of Blightmud. I've already brought up splitting the blight module into separate modules with more logical names and responsibilities.

I'm thinking that we could while we do this move the new modules to pure lua. Instead of handling triggers and stuff in lua we will instead send all received lines through lua before being rendered. The triggers etc could then be completely isolated to the lua context. Naturally we will do the same for user input. This requires the regex issue to be completed and also a lua object representing a line to be created. Giving the user access to its flags and raw/clean content (like line.rs). We could even let the user modify the line before its printed.

**Comment by LiquidityC** [comment]
Adding a infinite loop safety after this has been done should be child's play. I'm thinking a line hook which breaks if you reach a line count > 1000 or something. This can easily be made modifiable.

**Comment by LiquidityC** [comment]
Also @Xandaros gave me this idea. He should have some credit 😉
