### ISSUE TITLE
Input line editing shortcuts.

### ISSUE THREAD

**Issue by lisdude** [LiquidityC/Blightmud#24]
With long commands, it would be nice to have an easy way to get around the input line. Here are my proposed changes:

- [ ] `Home`
    - Output view / scrolling mode: Move to the top of the output view.
    - Input mode: Move to the beginning of the input line.
- [ ] `End`
    - Output view: Stays the same. Move to the bottom of the output view.
    - Input mode: Move to the end of the line.
- [ ] `Alt-Backspace`
    - Input mode: Clear the entire input line.
- [ ] `Ctrl-Backspace`
    - Delete one word back
- [ ] `Alt-left` or `Ctrl-left`
    - Input mode: Move back a word.
- [ ] `Alt-right` or `Ctrl-right`
    - Input mode: Move forward a word.

Short of full Vim or Emacs emulation, I think these would be good! Even better if it's customizable.

**Comment by LiquidityC** [comment]
All these suggestions seem fine. No comments. However, we should/will differentiate between scrolling and input mode when the "(more)" label is shown.
**Meaning:** To get into scrolling mode you need to hit `PgUP`

**Comment by LiquidityC** [comment]
Edited the main comment for nicer tracking. Also added ctrl - left/right bindings (these are common in many word processors)

**Comment by LiquidityC** [comment]
This one turned out to be more difficult then expected. Partially because there is no standard for Ctrl-<special key> for different terminals. Hence the tty lib we use doesn't have any practical support for it. Secondly because command input and the output view are rather decoupled so it's hard to know if we are in input or scolling mode. Removing from milestone for now

**Comment by LiquidityC** [comment]
Closing this and adding #43 to cover some of the cases
