### ISSUE TITLE
Additional Lua commands

### ISSUE THREAD

**Issue by lisdude** [LiquidityC/Blightmud#30]
blight:terminal_width()
Return the width of the user's terminal.
(why? MOOs have a setting for maximum line length. There's an MCP package that will automatically set your linewidth for you, but we need to know the width of the terminal to do it.)

blight:version([1 || 2])
No arguments: Return the name and version of the client. e.g. "Blightmud 0.1.0"
With argument 1: Return only the name of the client.
With argument 2: Return only the numeric version.
(why? The MCP client package reports the client name and version to the MOO. Always nice to advertise your favorite client.)

blight:remove_trigger(regex)
Unregister a previously registered trigger.
(why? Part of the MOO MCP specification calls for package negotiation. Once it's done, though, it should be done forever. Removing the trigger would be nice to make sure it's done for good. I realize I could accomplish basically the same thing with a flag, so this is kind of a 'nice to have' thing more than a necessity.)

blight:send(str[, gag])
Add an optional argument to send to gag the line from appearing in local echo.

**Comment by LiquidityC** [comment]
No problem with these. Lua supports multiple return values so let us abuse that.

**Spec:**
- [ ] Add lua method: `blight:terminal_dimension() -> width, height`
- [ ] Add lua method: `blight:version() -> name, version`
- [ ] Update `blight:add_trigger() -> trigger_id`
- [ ] Add lua method: `blight:remove_trigger(trigger_id) -> void`
- [ ] Update `blight:add_alias() -> alias_id`
- [ ] Add lua method: `blight:remove_alias(alias_id) -> void`
- [ ] Update `blight:send(str[, gag: bool]) -> void` so that echo can be prevented (this might be tricky)

If you are new to rust and Blightmud. Picking one of these changes is fine. We can track them individually.
