### ISSUE TITLE
Parts of output are missing.

### ISSUE THREAD

**Issue by lisdude** [LiquidityC/Blightmud#36]
**Describe the bug**
Sometimes bits of output aren't displayed. This is possibly when data is in tables with long spaces? Not sure.

**To Reproduce**
1. /connect lisdude.com 1180
2. longline2

Repeat the longline2 command several times. Notice that there are gaps in different places each time.

**What terminal are you using?**
Kitty + tmux

**What mud were you playing?**
lisdude.com:1180

**Screenshots**
<img width="1165" alt="Screen Shot 2020-05-25 at 10 27 07 AM" src="https://user-images.githubusercontent.com/4994688/82826213-505db400-9e72-11ea-8562-9418eaef3628.png">

**Comment by LiquidityC** [comment]
It's not missing really. Looking at your output you can see that the line that is 'incomplete' is an identical prefix to the line below. This is because all the data is not sent in one continuous stream, rather it's truncated.

This testserver doesn't send IAC,GA commands so we have to guess if we have a prompt or not. When we're not certain, we guess that it's a prompt but keep the contents in buffer, just in case there is more data to get.

So what you are seeing is the received chunk followed by a guess at a prompt. We then instantly receive more data and prepend it with what we thought was a prompt on the last line. So data isn't lost. It's just a visual artifact.

If you have more info on how to correctly guess what's a prompt I'd love to hear it because I have no clue what else to do if we don't get a IAC,GA command.

**Comment by LiquidityC** [comment]
I have one solution after some testing that helps a tad. If we peek the stream before assuming we have a prompt to make sure there isn't more data coming then we get more accurate guessing. It's not perfect but it solves this particular case. Not sure how it would perform in other instances.

**Comment by LiquidityC** [comment]
Ignore my "potential" solution I mentioned above. It's not a solid option at all. :rofl:

**Comment by lisdude** [comment]
Ah, I'm not very observant I guess! 

MOOs don't have a prompt, so could we just say: /set prompt=off  ?

Then there's no need to guess what's a prompt because it's 100% certain that there isn't one. Or uh. I guess /set is global, so maybe a Lua toggle? (A bit sleep deprived here, thinking is hard work.)

**Comment by LiquidityC** [comment]
Not any easy problem. We have modes for "UnterminatedPrompt" eg. no IAC,GA, "TerminatedPrompt" eg. sends IAC,GA guess we could try to capture a 3:rd option "EmptyPrompt". But I don't want the user to have to bother about this crap. I want it to just work out of the box. Shouldn't be too hard to guess. But we really do need to avoid false positives.

I'll leave this one up for discussion.

**Comment by LiquidityC** [comment]
I've implemented a third "telnet mode" for the client which is the "NoPrompt" mode. This should provide nicer behavior on MOO's and remove the artifact mentioned in this issue. Should be in shortly.
