### ISSUE TITLE
Add config dir to lua path

### ISSUE THREAD

**Issue by Xandaros** [LiquidityC/Blightmud#72]
Currently, if you try to require a file in a script, it tries to load it from the working directory (where you started blight) and the system Lua paths. It does not try to load from `~/.config/blightmud`.

I think that path should be automatically searched, with higher priority than the system Lua.

--

I also just realised that all files in `~/.config/blightmud` are automatically loaded. Is it possible to prevent that?

**Comment by LiquidityC** [comment]
I chose not to mess with the package path in lua through blightmud. Mostly because I'm not that experienced with lua and thought that better left to the script developer to configure.

You can change it as you like within lua though:

```lua
package.path = "/path/to/your/script/folder/?.lua;" .. package.path
```

There is no real filtering option to decide what lua files we load from the config folder and which we don't. If the file ends in `.lua` it'll be loaded. Personally I only have one file in my config dir. That in turn loads other scripts depending on what server I connect to. Those scripts in turn modify the `package.path` so that `require` will work independently of where you started blightmud.

**Comment by LiquidityC** [comment]
Here is my `config.lua` from my blightmud config dir as an example:

```lua
local function reload_scripts()
	blight:status_height(1)
	blight:status_line(0, "")
	blight:reset()
	blight:load("/home/linus/.config/blightmud/config.lua")
end

blight:add_alias("^reload-script$", reload_scripts)
blight:on_disconnect(reload_scripts)

local connected = false
blight:on_connect(function (host, port)
	if host == "aetolia.com" then
		blight:load("/home/linus/ws/blightmud-scripts/aetolia/script.lua")
	elseif host == "achaea.com" then
		blight:load("/home/linus/ws/blightmud-scripts/achaea/script.lua")
	end 
end)
```

**Comment by Xandaros** [comment]
The reason I mentioned the possible option of filtering is that I would like to have all my scripts in one place, including all their dependencies. But I don't want them to all be loaded automatically.
In particular, I have a `credentials.lua`, which I prefer to load, use, and then purge from memory.

Do lua files in subdirectories get loaded? If not, that might be a nice workaround

**Comment by LiquidityC** [comment]
Subdirectories will not get loaded. Only lua files on first level in the config dir.

**Comment by LiquidityC** [comment]
Closing this. Don't think there's a "fixable" issue here.

**Comment by Xandaros** [comment]
I'm honestly still thinking about it.
As it is, `require` is basically useless, unless you change `package.path` yourself.
Changing `package.path`, using `dofile` or using `blight:load` all require the use of absolute paths. This would require the use of hardcoded paths, or determining the blightmud config directory manually, by reading environment variables.

Not really happy with any of those, if I'm being honest.
