### ISSUE TITLE
Add /lua command

### ISSUE THREAD

**Issue by Xandaros** [LiquidityC/Blightmud#78]
Sometimes it can be handy to run a piece of Lua code directly from within the program. This is particularly handy when working on your script and you quickly want to test something.

To that end, I suggest adding a `/lua` command, which executes it's arguments as Lua code:
`/lua blight:status_line(0, "Test")`

Since Lua doesn't actually require line breaks between statements, the code can be arbitrarily complex and multi-line support is not strictly necessary.

**Comment by LiquidityC** [comment]
I’ve already been pondering this. I’ll give it a whirl. Doesn’t seem like a too difficult thing to implement.

**Comment by robg204** [comment]
@Xandaros , @LiquidityC just as a follow up on this:  This was easy to implement in lua as a script as well.  Other clients that use lua do a similar thing -- it might be an interesting idea to include a standard lua library so that some things like this can be opt in/out, without cluttering up the client itself too much with things that can be done easily in lua.

Example (I've ported the supporting functions to make this work in my configuration, much of it could be simplified to lua 5.3 since the original source is lua 5.1).

`blight:add_alias("^lua (.*)$", function(matches)
    local f, e = load("return "..matches[2])
    if not f then
      f, e = assert(load(matches[2]))
    end
  
    local r =
      function(...)
        if not table.is_empty({...}) then
          display(...)
        end
      end
    r(f())
    end)`

**Comment by LiquidityC** [comment]
I do agree with you on this one @robg204. Since we have lua readily available we should use/have used it to extend default features and functionality instead of increasingly "complexifying" the core of the client.

Currently the json library is loaded into the lua environment on app start. We could easily add a common lua library to this cycle which adds additional features.
We just need to confirm that you can create aliases that start with a forward slash (for '/lua <code>' command).

I'm reopening this one and I'll have a look at it tonight unless someone beats me to it.

**Comment by Xandaros** [comment]
In general, I would agree that things that can be implemented in Lua, should be implemented in Lua. However, in this case I feel like it's too much of a core command.
You could also implement `/load` in Lua if you really wanted to.

I don't feel like these kinds of commands - reading scripts, evaluating code, etc. should be implemented in Lua. I'd consider them core functionality.

**Comment by robg204** [comment]
> In general, I would agree that things that can be implemented in Lua, should be implemented in Lua. However, in this case I feel like it's too much of a core command.
> You could also implement `/load` in Lua if you really wanted to.
> 
> I don't feel like these kinds of commands - reading scripts, evaluating code, etc. should be implemented in Lua. I'd consider them core functionality.

I agree for stuff like load, however in the case of /lua, my reasoning is not that it isn't "core", but moreso that the result is just generally better if it's provided in lua.  For instance: my port of the mudlet lua command uses prettyprint, so rather than:

```
/lua t = {"one", "two"}
/lua t
table
```

You get:
```
lua t
{
  "one",
  "two"
}
```
It's subsequently easier for users to extend with other such features for handling other types of data as well.

You can check this out, if you wish, at [this gist](https://gist.github.com/robg204/4783bb944c05a500ff051c4dff0903a4).

**Comment by Xandaros** [comment]
All right, that's fair. I actually am quite unhappy with it just printing `table`, even though that is pretty close to standard Lua behaviour:
```
> {}
table: 0x5571674a9f60
```
In general, I think actually printing what is in the table is the better option.
It should definitely have a slash in front, though - creating aliases with a slash in front is possible, I just tried it.

**Comment by LiquidityC** [comment]
Just a quick note on **core features**. In my mind the blightmud core is the following:

- The telnet connection
- The telnet protocols
- Displaying output and transmitting input
- Bindings to lua through aliases, triggers, timers and commands

Quality of life commands and logic rich functionality should be implemented in lua using this core lua api. If the core api doesn't provide the requirements to implement a feature in lua then we extend the core. Otherwise we implement in lua right away.

This is something that my train of thought has boiled down to during the day. The intention is to keep the core implementation at the lowest possible complexion level. In short. This is based on experience from game development where you have the messy logic in lua and the clean easy to read core game in Rust (C in my previous work).

New features should then have less impact on the client, hopefully resulting in less bugs.

**Comment by LiquidityC** [comment]
I kinda went rogue and added this because I wanted to test it out. Comments?

**Comment by robg204** [comment]
It looks right to me, if it seems to be working right, I'm happy with that.  The port could use a bit of further lua cleanup, but that's some light maintenance that can happen any time.  :)
