### ISSUE TITLE
Alt-Backspace to delete a word in the input

### ISSUE THREAD

**Issue by Xandaros** [LiquidityC/Blightmud#79]
Pressing Alt-Backspace should delete from the current cursor position to the previous space (not including the space)

Basically how most shells behave by default

**Comment by LiquidityC** [comment]
This has been brought up before in #24 
I have a possible idea for adding this support through user configuration but for now It's not something I will focus on. Default terminal shortcuts work:
- `ctrl-a`
- `ctrl-e`
- `alt-f`
- `alt-b`

**Comment by Xandaros** [comment]
Alt-Backspace IS a default terminal shortcut :stuck_out_tongue: At least in bash and fish.
As are Alt-Left and Alt-Right to move by entire words.

**Comment by LiquidityC** [comment]
Yes, but vt102 from what I've read doesn't have standard events for `ctrl-<special>` where special is ´backspace` or `enter` or `backtab` etc.

At least not through termion. There is an unknown event you can receive when this happens that provides you with a byte sequence. A solution I thought of was printing this byte string when a user attempts the command. The user can then be offered the possibility to bind commands to these byte strings in order to configure keybindings. From what I can tell those bytestrings can differ between terminal types.

This might require more then an hours research which is what I put in roughly. But that's where we stand right now.

**Comment by LiquidityC** [comment]
Once #128 is done it should be possible to configure all of this to your liking. Closing this one.
